language: java
jdk:
  - openjdk11
branches:
  only:
  - dev
cache:
  directories:
  - $HOME/.m2
notifications:
  flowdock:
    secure: K1UtEY7LkEwuhjKTTSHgMSwHyvX5iIrb+/GtjUh6/nPTeZm1Pko0NOMy/DMKCLMfTyrumuTUVLi2R17AOUciSeCSB1gtTirBsLByfI6wWJE68zjKzesJG6mmuF16/N5V/7758Mfn5K8SAtPoPoyZS/2gA6B8S/NK5tZa9+1eXY4Pz223bVBOgqoxzjCJK15KVXAcjDOn5eFGf2hZc9+ypYw0f7JWWrS62eQ4N0VblShBISa73Boh5dTigsW6KwMEhOxA/NM/xk+kruyDiEJqZCNIZWznwPQCKG8hPel7t2Jx6KEOHDHnMclETGwbx1VEx1JEr36SDDb1L16bLxxoAmh9N6xw3+kCXhNp3xU6afFE1cAeMeyEJfbVU/KTEi2TNe7xz7MYU2yjVN7KmwjDmZswe0Hc7+xaq8v0PcoVXa3CysfDPXldswcKH2XzzNtC7kXWtBZua6LNuXNRYDKvZaesv5bh8hHJIDIbnLCLeErCbQ859agAQQQXplAQIw3ZIZAaU6fm4nYS55G18npYsl3IoKizL49CQmFj/YrnVol+ruzejJQMASb2ilvXhc12CTQJRN4ueX967z2kbcg+acgcR1pCN92hLqXgwtBOgNUggWw90f/Zn8EnOMrJXzDlswMpDt7UR2t17bxbW3psHWsbe14hfdom9hLN0B1n7g0=

