language: java
jdk:
  - openjdk11
branches:
  only:
  - dev
cache:
  directories:
  - $HOME/.m2
notifications:
  flowdock:
    secure: E5jr8O49LLHYRyMEBD3ctk9gNs7IYCdjWD32usjfuw3R3Ahr5Ivg4qTbT/3Atc9nvY0nQdJWr1jlZCSD82FFmZM6nxsE1G1Phy29n7ysWuD+1V07axvZiv6Hlrm788Tr2jcWiH855ftAyqWhu+/1l22uReNQLz7ahNt+DPLK1iJpjadIk/1n96QhAIf3CMQH6ya9q5eFngSkKt/7yF41w7sqWqOgZGfUcKcZjFD3HJWAdHxhA/olx6C5Ae51+1/ycwKJj9vAo7RGSLGBPR3O6uoRT2Gia3xf7qXcnuJFoK7sXTsbGBYaa6hhdShuMN6xfh81eXTMykhBkHtEeH7fPKbnloDLYFfjH8HVvW8HKaAyUak2IYe3wfndt5T+FdbG18gZ/hbzu3BdNXrRj+mPIiOmIHEVWMLItOX7zF8UtFwtOINHKdxIHKmymTejWTp7FN4skJkyf6p4svBqUGZ7aBBoPQ3rjD5NGDUUoYtZqS8qTJTURWG5B2QNjFQN2TVTCBtA6XLq3FqI+9fX7xj+PTjynJXauDlOcBuuVQhPuqXGFmN2Mi+qJt1qsmbyu7Bshym23xdMzBUT4pj4FJVGzczHrqbmPkbNE444+nW4UgZ6qaUCjlqPW8VtonAjzPEjY2wWY8fAFq02Uqe26m6t0eBphwdBDtpP7HtTFBX/Y9A=
