apiVersion: v1
kind: Pod
metadata:
  labels:
    app: smearregressiontest
  name: smearregressiontest
spec:
  containers:
    - image: >-
        docker-registry.default.svc:5000/avaa-smear-new-conf/smearregressiontest:latest
      imagePullPolicy: Always
      name: smearregressiontest
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - mountPath: /smear-rahti/robot_tests/regression_test_reports
          name: smearregressiontest
          subPath: jobs/Smear_Regression_Test/workspace/regression_test_reports
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-d2xmq
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: smearregressiontest
      persistentVolumeClaim:
        claimName: jenkins
    - name: default-token-d2xmq
      secret:
        defaultMode: 420
        secretName: default-token-d2xmq