apiVersion: v1
kind: BuildConfig
metadata:
  name: smearsmoketest
spec:
  runPolicy: "Serial"
  source:
    contextDir: openshift
    git:
      ref: dev
      uri: 'https://github.com/CSCfi/smear-rahti'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: smearsmoketest.Dockerfile
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'smearsmoketest:latest'
      namespace: avaa-smear-new-conf
  triggers:
  - github:
      secretReference:
        name: smear-github-webhook
    type: GitHub
